files:
  - source: /docs/about/**/*.md
    translation: /docs/%two_letters_code%/about/%original_file_name%
  - source: /docs/friendly/**/*.md
    translation: /docs/%two_letters_code%/friendly/%original_file_name%
  - source: /docs/life/**/*.md
    translation: /docs/%two_letters_code%/life/%original_file_name%
  - source: /docs/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
  - source: /docs/tips/**/*.md
    translation: /docs/%two_letters_code%/tips/**/%original_file_name%
  - source: /README.md
    translation: /%file_name%_%two_letters_code%.md
