name: Auto Approve & Merge PR for Specific User

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'imgbot'
    steps:
      - name: Approve PR
        run: |
          gh pr review "$PR_URL" --approve
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Squash Merge and Delete Branch
        run: |
          gh pr merge "$PR_URL" --squash --delete-branch
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Add label
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "Actions"

      - name: Approve PR
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve

      - name: Squash Merge and Delete Branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch
