name: 部署到 Cloudflare Pages

on:
  push:
    branches:
      - 'main' # 当推送到 main 分支时触发
    paths:
      - 'docs/**'
      - '.github/workflows/cf.yml'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.3

      - name: 安装依赖
        run: pnpm install

      - name: 更新主题包
        run: pnpm update @project-trans/vitepress-theme-project-trans@prerelease

      - name: 构建项目
        run: pnpm run build # 构建 VitePress 项目

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_PAGES_ACCOUNT }}
          command: pages deploy docs/.vitepress/dist --project-name=blog

      # - name: 使用 wrangler 命令输出
      #   env:
      #     CMD_OUTPUT: ${{ steps.deploy.outputs.command-output }}
      #   run: echo $CMD_OUTPUT

      # - name: 单独输出预览URL
      #   run: echo ${{ steps.deploy.outputs.deployment-url }}
