name: Deploy to Cloudflare Pages

on:
  # push:
  #   branches:
  #     - 'main' # 当推送到 main 分支时触发
  #   paths:
  #     - 'docs/**'
  #     - '.github/workflows/cf.yml'
  #     - '.github/workflows/deploy-to-server.yml'
  #     - 'package.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Update theme package
        run: pnpm update @project-trans/vitepress-theme-project-trans@prerelease

      - name: Build project
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_PAGES_ACCOUNT }}
          command: pages deploy docs/.vitepress/dist --project-name=blog

      # - name: 使用 wrangler 命令输出
      #   env:
      #     CMD_OUTPUT: ${{ steps.deploy.outputs.command-output }}
      #   run: echo $CMD_OUTPUT

      # - name: 单独输出预览URL
      #   run: echo ${{ steps.deploy.outputs.deployment-url }}
