name: Deploy to server

on:
  # push:
  #   branches:
  #     - 'main'
  #   paths:
  #     - 'docs/**'
  #     - '.github/workflows/cf.yml'
  #     - '.github/workflows/deploy-to-server.yml'
  #     - 'package.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Update theme package
        run: pnpm update @project-trans/vitepress-theme-project-trans@prerelease

      - name: Build project
        run: pnpm run build

      - name: Deploy to Server via SSH rsync
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          ARGS: "-avz --delete --progress"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "docs/.vitepress/dist/"
          TARGET: "/var/www/blog/"
